### ISSUE TITLE
format

### ISSUE THREAD

**Issue by branislavrajkov** [branislavrajkov/devopsconbootcamp#2]
- [ ] fix problem No1
- [ ] clone repo

**bold text**

**Comment by branislavrajkov** [comment]
```mermaid
graph RL;
    7e536==>96a85;
    b7e6b==>7e536;
    main-.->b7e6b;
    HEAD-->main;
    55805==>7e536;
    branch-.->55805;
    tag-.->55805;
```

**Comment by branislavrajkov** [comment]
- [ ] stavi chart

```mermaid
graph RL;
    begining==>crossroad;
    road1==>crossroad;
    bicycle-.->road1;
    driver-->road1;
    55805==>crossroad;
    man-.->road2;
    woman-.->road2;
```

**Comment by branislavrajkov** [comment]
### yaml:
```yaml
references:
  ### ADMIN CONSOLE API
  adminApiBaseUrl: &adminApiBaseUrl "http://{{ requiredEnv `ASEE_ADMIN_CONSOLE_INGRESS_HOST` }}"
  adminAuthUrl: &adminAuthUrl "http://{{ requiredEnv `ASEE_ADMIN_CONSOLE_INGRESS_HOST` }}/v1/authentication"

  ### AUTHENTICATION
  authenticationUrl: &authenticationUrl "http://{{ requiredEnv `ASEE_INGRESS_HOST` }}/v1/authentication"


  ingressHost: &ingressHost "{{ requiredEnv `ASEE_INGRESS_HOST` }}"

  databaseName: &databaseName "abc_ite3"
  databaseUsername: &databaseUsername "kiteu"
  databasePassword: &databasePassword "{{ requiredEnv `ASEE_DATABASE_PASSWORD` }}"

  ### STORAGE
  storageEnabled: &storageEnabled true
  storageClass: &storageClass "rook-ceph-block"
```
